// swift-tools-version:5.9
// Native macOS Swift Package for MediaPipe Vision Tasks (Hand/Pose/Face landmarkers).
//
// NOTE: This package depends on a locally-built binary artifact:
//   mediapipe/tasks/macos/swift/Artifacts/MediaPipeTasksC.xcframework
// That artifact is generated by `mediapipe/tasks/macos/build_macos_xcframework.sh`
// and is intentionally gitignored. You MUST run that script before `swift build`,
// otherwise SwiftPM will fail to resolve the `CMediaPipeTasksC` binary target.
// See mediapipe/tasks/macos/README.md.
import PackageDescription
import Foundation

let swiftRoot = "mediapipe/tasks/macos/swift"

// Set MP_LOCAL_XCFRAMEWORK=1 to link the locally-built artifact under
// Artifacts/ (produced by build_macos_xcframework.sh) instead of the released
// binary. Used to test changes baked into the compiled MediaPipe graph.
let useLocalXCFramework = ProcessInfo.processInfo.environment["MP_LOCAL_XCFRAMEWORK"] != nil

let cMediaPipeTasksC: Target = useLocalXCFramework
    ? .binaryTarget(
        name: "CMediaPipeTasksC",
        path: "\(swiftRoot)/Artifacts/MediaPipeTasksC.xcframework")
    : .binaryTarget(
        name: "CMediaPipeTasksC",
        url: "https://github.com/smlntsv/mediapipe/releases/download/v0.10.35-macos.1/MediaPipeTasksC.xcframework.zip",
        checksum: "37038256ecb537c2c2a2c08a2c52a885aae4b4879521904debe8751f046e9587")

let package = Package(
    name: "MediaPipeTasksMac",
    platforms: [
        .macOS(.v13)
    ],
    products: [
        .library(name: "MediaPipeTasksMac", targets: ["MediaPipeTasksMac"]),
        .executable(name: "mediapipe-macos-sample", targets: ["MediaPipeMacSample"]),
    ],
    targets: [
        // Binary runtime only: the compiled macOS MediaPipe C symbols
        // (MpHandLandmarker*, MpImage*, ...). Not imported by Swift directly.
        // Remote release by default; local build when MP_LOCAL_XCFRAMEWORK=1.
        cMediaPipeTasksC,

        // Objective-C++ bridge. Includes the MediaPipe C headers straight from the
        // repo source tree and links the binary above. Swift only ever sees the
        // Objective-C wrapper classes declared in this target's `include/` dir.
        .target(
            name: "MediaPipeTasksObjC",
            dependencies: ["CMediaPipeTasksC"],
            path: "\(swiftRoot)/Sources/MediaPipeTasksObjC",
            cxxSettings: [
                // Reach the repo root so `#include "mediapipe/tasks/c/..."` resolves.
                .headerSearchPath("../../../../../..")
            ]
        ),

        // Public Swift API.
        .target(
            name: "MediaPipeTasksMac",
            dependencies: ["MediaPipeTasksObjC"],
            path: "\(swiftRoot)/Sources/MediaPipeTasksMac"
        ),

        // Minimal CLI sample.
        .executableTarget(
            name: "MediaPipeMacSample",
            dependencies: ["MediaPipeTasksMac"],
            path: "\(swiftRoot)/Sources/Sample"
        ),

        // Tests that verify result shapes/counts. They run only when the
        // relevant model/image paths are provided via environment variables
        // (see the test file); otherwise each case is skipped.
        .testTarget(
            name: "MediaPipeTasksMacTests",
            dependencies: ["MediaPipeTasksMac"],
            path: "\(swiftRoot)/Tests/MediaPipeTasksMacTests"
        ),
    ],
    cxxLanguageStandard: .cxx20
)
