// swift-tools-version:5.9
// Multiplatform (macOS + iOS) Swift Package for MediaPipe Vision Tasks
// (Hand/Pose/Face landmarkers), incl. the Core ML / ANE delegate.
//
// NOTE: This package depends on a locally-built binary artifact:
//   mediapipe/tasks/macos/swift/Artifacts/MediaPipeTasksC.xcframework
// That artifact is generated by `mediapipe/tasks/macos/build_macos_xcframework.sh`
// and is intentionally gitignored. You MUST run that script before `swift build`,
// otherwise SwiftPM will fail to resolve the `CMediaPipeTasksC` binary target.
// See mediapipe/tasks/macos/README.md.
import PackageDescription
import Foundation

let swiftRoot = "mediapipe/tasks/macos/swift"

// Link the locally-built artifact under Artifacts/ (produced by the build
// scripts) instead of the released binary when EITHER MP_LOCAL_XCFRAMEWORK is
// set OR the artifact simply exists on disk. The on-disk check is what makes
// the local universal xcframework work when the package is consumed as a
// LOCAL package from Xcode (e.g. the iOS test app): Xcode evaluates the
// manifest in a sandbox that does not inherit shell/scheme environment
// variables, so the env-var gate alone never fires there. Consumers that pull
// the package by revision from GitHub have no Artifacts/ dir and fall through
// to the released binary, so their behavior is unchanged.
let localXCFrameworkPath = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()
    .appendingPathComponent("\(swiftRoot)/Artifacts/MediaPipeTasksC.xcframework")
    .path
let useLocalXCFramework = ProcessInfo.processInfo.environment["MP_LOCAL_XCFRAMEWORK"] != nil
    || FileManager.default.fileExists(atPath: localXCFrameworkPath)

let cMediaPipeTasksC: Target = useLocalXCFramework
    ? .binaryTarget(
        name: "CMediaPipeTasksC",
        path: "\(swiftRoot)/Artifacts/MediaPipeTasksC.xcframework")
    : .binaryTarget(
        name: "CMediaPipeTasksC",
        url: "https://github.com/smlntsv/mediapipe/releases/download/v0.10.35-macos.3/MediaPipeTasksC.xcframework.zip",
        checksum: "fc9b4a15184dc3e9005f96d5963d3958db371435d15c1b9f0ce3c566c1531a22")

let package = Package(
    // Renamed from "MediaPipeTasksMac" once the package became multiplatform:
    // the binary target is a universal MediaPipeTasksC.xcframework carrying
    // macOS, iOS-device and iOS-simulator slices, and the ObjC++ bridge + Swift
    // API are platform neutral (Foundation + CoreGraphics/CoreVideo + the C API
    // — no AppKit). iOS 17 / macOS 14 is the Core ML (ANE) floor for the
    // converted models. Consumers on the old name keep working by staying
    // pinned to a pre-rename revision; to update, change `import
    // MediaPipeTasksMac` → `import MediaPipeTasks` and the SPM product name.
    name: "MediaPipeTasks",
    platforms: [
        .macOS(.v13),
        .iOS(.v17),
    ],
    products: [
        .library(name: "MediaPipeTasks", targets: ["MediaPipeTasks"]),
        .executable(name: "mediapipe-macos-sample", targets: ["MediaPipeMacSample"]),
    ],
    targets: [
        // Binary runtime only: the compiled macOS MediaPipe C symbols
        // (MpHandLandmarker*, MpImage*, ...). Not imported by Swift directly.
        // Remote release by default; local build when MP_LOCAL_XCFRAMEWORK=1.
        cMediaPipeTasksC,

        // Objective-C++ bridge. Includes the MediaPipe C headers straight from the
        // repo source tree and links the binary above. Swift only ever sees the
        // Objective-C wrapper classes declared in this target's `include/` dir.
        .target(
            name: "MediaPipeTasksObjC",
            dependencies: ["CMediaPipeTasksC"],
            path: "\(swiftRoot)/Sources/MediaPipeTasksObjC",
            cxxSettings: [
                // Reach the repo root so `#include "mediapipe/tasks/c/..."` resolves.
                .headerSearchPath("../../../../../..")
            ]
        ),

        // Public Swift API.
        .target(
            name: "MediaPipeTasks",
            dependencies: ["MediaPipeTasksObjC"],
            path: "\(swiftRoot)/Sources/MediaPipeTasks"
        ),

        // Minimal CLI sample.
        .executableTarget(
            name: "MediaPipeMacSample",
            dependencies: ["MediaPipeTasks"],
            path: "\(swiftRoot)/Sources/Sample"
        ),

        // Tests that verify result shapes/counts. They run only when the
        // relevant model/image paths are provided via environment variables
        // (see the test file); otherwise each case is skipped.
        .testTarget(
            name: "MediaPipeTasksTests",
            dependencies: ["MediaPipeTasks"],
            path: "\(swiftRoot)/Tests/MediaPipeTasksTests"
        ),
    ],
    cxxLanguageStandard: .cxx20
)
