// swift-tools-version:5.9
// Native macOS Swift Package for MediaPipe Vision Tasks (Hand/Pose/Face landmarkers).
//
// NOTE: This package depends on a locally-built binary artifact:
//   mediapipe/tasks/macos/swift/Artifacts/MediaPipeTasksC.xcframework
// That artifact is generated by `mediapipe/tasks/macos/build_macos_xcframework.sh`
// and is intentionally gitignored. You MUST run that script before `swift build`,
// otherwise SwiftPM will fail to resolve the `CMediaPipeTasksC` binary target.
// See mediapipe/tasks/macos/README.md.
import PackageDescription

let swiftRoot = "mediapipe/tasks/macos/swift"

let package = Package(
    name: "MediaPipeTasksMac",
    platforms: [
        .macOS(.v13)
    ],
    products: [
        .library(name: "MediaPipeTasksMac", targets: ["MediaPipeTasksMac"]),
        .executable(name: "mediapipe-macos-sample", targets: ["MediaPipeMacSample"]),
    ],
    targets: [
        // Binary runtime only: the compiled macOS MediaPipe C symbols
        // (MpHandLandmarker*, MpImage*, ...). Not imported by Swift directly.
        .binaryTarget(
            name: "CMediaPipeTasksC",
            path: "\(swiftRoot)/Artifacts/MediaPipeTasksC.xcframework"
        ),

        // Objective-C++ bridge. Includes the MediaPipe C headers straight from the
        // repo source tree and links the binary above. Swift only ever sees the
        // Objective-C wrapper classes declared in this target's `include/` dir.
        .target(
            name: "MediaPipeTasksObjC",
            dependencies: ["CMediaPipeTasksC"],
            path: "\(swiftRoot)/Sources/MediaPipeTasksObjC",
            cxxSettings: [
                // Reach the repo root so `#include "mediapipe/tasks/c/..."` resolves.
                .headerSearchPath("../../../../../..")
            ]
        ),

        // Public Swift API.
        .target(
            name: "MediaPipeTasksMac",
            dependencies: ["MediaPipeTasksObjC"],
            path: "\(swiftRoot)/Sources/MediaPipeTasksMac"
        ),

        // Minimal CLI sample.
        .executableTarget(
            name: "MediaPipeMacSample",
            dependencies: ["MediaPipeTasksMac"],
            path: "\(swiftRoot)/Sources/Sample"
        ),
    ],
    cxxLanguageStandard: .cxx20
)
